### ISSUE TITLE
mysql: converting  ColumnType::MYSQL_TYPE_VAR_STRING to DataType::Binary

### ISSUE THREAD

**Issue by hozan23** [datafusion-contrib/datafusion-table-providers#95]
Hello, 

Any reason why converting ColumnType::MYSQL_TYPE_VAR_STRING to a binary [here](https://github.com/hozan23/datafusion-table-providers/blob/main/src/sql/arrow_sql_gen/mysql.rs#L468). 

I have a issue where it converts to binary even if it's a string. 

I tried fixing it by removing the if statement and converting it to DataType::LargeUtf8. [fix](https://github.com/hozan23/datafusion-table-providers/commit/2e7e8f574446abbc9c60b2555482da7e1b5ade79)

**Comment by Sevenannn** [comment]
Hello @hozan23, thanks for raising the issue and contributing! Would you please provide some details on which concrete MYSQL type you are having trouble with?
Since MYSQL_TYPE_VAR_STRING can represent both `CHAR` and `BINARY` MySQL types, we do distinguish here so that MySQL `CHAR` is converted to arrow `DataType::LargeUtf8` and MySQL `BINARY` is converted to arrow `DataType::Binary`.

**Comment by sgrebnov** [comment]
@hozan23 - thank you for reporting this, could you please elaborate more on specific issue/scenario so we make sure it is addressed:
  >I have a issue where it converts to binary even if it's a string.

**Comment by hozan23** [comment]
Hey @sgrebnov and @Sevenannn, thanks for the quick responses.

After attempting to replicate the issue with the same data, I noticed that it doesn't originate from this part. It seems to be related to issue #18. The parsing of expressions to SQL doesn't wrap the column and table names correctly, which results in incorrect types for some columns.

I'll close this issue now, as I'm already working on a PR for issue #18. I'll push the PR soon.
